### ISSUE TITLE
💾 Add ability to specify secondary_storage for default and GPU worker pool

### ISSUE THREAD

**Issue by l2fprod** [IBM/roks-openshift-ai-da#2]
When using the DA, GPU nodes can quickly reach disk pressure with several users creating Data Science Workbenches and notebooks -- as by default they only have 100GB of primary storage.

The underlying base-ocp module supports the secondary_storage option
https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/d3c8a3dd6844ba66ddef88b62a206c4e394f4076/variables.tf#L72

but it is not exposed in the DA
https://github.com/IBM/roks-openshift-ai-da/blob/f66ff40aad31ee60044a353132d00508097be4b0/main.tf#L164

---

- [ ] add new optional input variable `gpu-secondary-storage` for the GPU worker pool in https://github.com/IBM/roks-openshift-ai-da/blob/f66ff40aad31ee60044a353132d00508097be4b0/variables.tf#L23
- [ ] use the new variable https://github.com/IBM/roks-openshift-ai-da/blob/f66ff40aad31ee60044a353132d00508097be4b0/main.tf#L173
- [ ] expose variable in https://github.com/IBM/roks-openshift-ai-da/blob/f66ff40aad31ee60044a353132d00508097be4b0/ibm_catalog.json#L181 
- [ ] update inputs https://github.com/IBM/roks-openshift-ai-da/blob/f66ff40aad31ee60044a353132d00508097be4b0/README.md?plain=1#L69 and add example of the values it can take is `300gb.5iops-tier`)

**Comment by darrellschrag** [comment]
added secondary storage to the GPU worker pool.
